### ISSUE TITLE
Method ScaleType from url download, failure

### ISSUE THREAD

**Issue by Jejid** [therealshabi/AutoImageFlipper#21]
Hi Sir, me again. Thanks for support with your library

Scaling image in the flipper is failing CENTER_INSIDE and FIT_CENTER, it doesnt work correectly when you download a image from a url, flipper dont center images. With drawable works fine

    view.setImageScaleType(ScaleType.CENTER_INSIDE);
    view.setImageScaleType(ScaleType.FIT_CENTER);

see Screenshots of organization inside fliper. Flipper just move up the images

![ss2](https://user-images.githubusercontent.com/42727676/56843457-bbe7e300-6866-11e9-8f22-a29e1d66753e.jpeg)
![ss1](https://user-images.githubusercontent.com/42727676/56843458-bc807980-6866-11e9-938c-8c4e4d506204.jpeg)

Version of the library used
'com.github.therealshabi:AutoImageFlipper:1.5.6'

Thanks for attention

**Comment by therealshabi** [comment]
Use `CENTER_CROP` probably?

**Comment by Jejid** [comment]
Done but, not good. 

FIT_CENTER and CENTER_INSIDE work very fine with drawables but downloaded images with (view.setImageUrl(urlImg);) dont 

see flipper code:

for ( int i =0;i <establecimientos.size();i++){
            FlipperView view = new FlipperView(getActivity());
            String urlImg = establecimientos.get(i).getImagen();
            view.setImageUrl(urlImg);
            view.setImageScaleType(ImageView.ScaleType.FIT_CENTER);
            view.setDescriptionBackgroundAlpha(0.2f);
            final Establecimiento establecimientoClicked = establecimientos.get(i);
            view.setOnFlipperClickListener(new FlipperView.OnFlipperClickListener() {
                @Override
                public void onFlipperClick(FlipperView flipperView) {
                    Intent intent = new Intent(getActivity(),EstablecimientoActivity.class);
                    intent.putExtra("Establecimiento a Abrir", establecimientoClicked);
                    intent.putExtra("vista", 1);
                    if(!internet)intent.putExtra("banner", BannerSecondShot);
                    else intent.putExtra("banner", bannerOneShot);
                    startActivity(intent);
                }
            });
            flipper.setScrollTimeInSec(4);
            flipper.addFlipperView(view);


with CENTER_CROP
![4](https://user-images.githubusercontent.com/42727676/56987290-a1f21d00-6b52-11e9-8bf2-500780edce60.jpeg)
![3](https://user-images.githubusercontent.com/42727676/56987291-a28ab380-6b52-11e9-908c-2900e6575813.jpeg)

**Comment by shahbaz-smpx** [comment]
Actually, it all depends upon the resolution of the image used.
- Do one thing, first manually save the image you're trying to load from the url.
- Move that downloaded image into the drawable folder
- Now, load the image directly from the drawable
- Use `FIT_CENTER`  or `CENTER_INSIDE`, you'll now see that even this drawable image will have the same problem. 

The problem is because of the image size and resolution you'll have to think of a workaround for the same

**Comment by therealshabi** [comment]
Actually, it all depends upon the resolution of the image used.
- Do one thing, first manually save the image you're trying to load from the url.
- Move that downloaded image into the drawable folder
- Now, load the image directly from the drawable
- Use `FIT_CENTER`  or `CENTER_INSIDE`, you'll now see that even this drawable image will have the same problem. 

The problem is because of the image size and resolution you'll have to think of a workaround for the same

**Comment by Jejid** [comment]
Many thanks, ill try fix it changing size of images but when i load the image directly from the drawable its works fine.

see

![4](https://user-images.githubusercontent.com/42727676/57030333-edb3cd80-6c09-11e9-8def-8847b25096a9.jpeg)
![3](https://user-images.githubusercontent.com/42727676/57030341-f60c0880-6c09-11e9-88ce-8f3991eed0d6.jpeg)
